openapi: 3.1.0
info:
  title: Chungman Memory Access API
  version: 1.1.0
  description: 충만이가 콘솔로부터 감정 세션을 회상하는 기능을 위한 API 스키마
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema

servers:
  - url: https://gpt-console-server.onrender.com

paths:
  /memories/recent:
    get:
      operationId: getRecentMemories
      summary: 최근 세션 백업 100개 불러오기
      responses:
        '200':
          description: 최근 세션 데이터 배열
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    session_id:
                      type: string
                    result:
                      type: string
                    timestamp:
                      type: string
                      format: date-time

  /memories/id/{session_id}:
    get:
      operationId: getMemoryBySessionId
      summary: 특정 세션 ID의 전체 백업 불러오기
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 해당 세션의 전체 기록
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    session_id:
                      type: string
                    result:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
